"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-30

NOTE: Hand-written rather than autogenerated — this sandbox has no network
access to install the `alembic` package, so `alembic revision --autogenerate`
could not actually be run here. This mirrors app/models/*.py field-for-field;
run `alembic check` locally after installing deps to confirm it matches
before applying to a real database.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _provenance_columns():
    return [
        sa.Column("source", sa.String(120), nullable=False, server_default="simulated"),
        sa.Column("source_id", sa.String(200), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(200), nullable=True),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("is_simulated", sa.Boolean, nullable=False, server_default=sa.true()),
    ]


def upgrade() -> None:
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(120), nullable=False, unique=True),
        sa.Column("agency", sa.String(120), nullable=False),
        sa.Column("adapter_type", sa.String(60), nullable=False),
        sa.Column("base_url", sa.String(500), nullable=True),
        sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("polling_interval_seconds", sa.Integer, nullable=True),
        sa.Column("authentication_type", sa.String(60), nullable=False, server_default="none"),
        sa.Column("reliability_score", sa.Float, nullable=False, server_default="0.7"),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(500), nullable=True),
    )

    op.create_table(
        "disaster_events",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("source_event_id", sa.String(200), nullable=False, index=True),
        sa.Column("lifecycle", sa.String(20), nullable=False, server_default="new"),
        sa.Column("hazard_type", sa.String(40), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("certainty", sa.String(20), nullable=False, server_default="unknown"),
        sa.Column("headline", sa.String(300), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("geometry_geojson", sa.Text, nullable=True),
        sa.Column("affected_area", sa.String(300), nullable=True),
        sa.Column("metadata_json", sa.Text, nullable=True),
        sa.Column("supersedes_id", sa.Integer, sa.ForeignKey("disaster_events.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        *_provenance_columns(),
    )

    op.create_table(
        "settlements",
        sa.Column("id", sa.String(60), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("district", sa.String(120), nullable=False),
        sa.Column("state", sa.String(120), nullable=False),
        sa.Column("population", sa.Integer, nullable=False, server_default="0"),
        sa.Column("vulnerable_population", sa.Integer, nullable=False, server_default="0"),
        sa.Column("risk_metadata", sa.Text, nullable=True),
        sa.Column("lat", sa.Float, nullable=False),
        sa.Column("lon", sa.Float, nullable=False),
        *_provenance_columns(),
    )

    op.create_table(
        "bridges",
        sa.Column("id", sa.String(60), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="open"),
        sa.Column("conflicting_sources", sa.Text, nullable=True),
        sa.Column("dependent_route_ids", sa.Text, nullable=True),
        sa.Column("lat", sa.Float, nullable=False),
        sa.Column("lon", sa.Float, nullable=False),
        *_provenance_columns(),
    )

    op.create_table(
        "road_segments",
        sa.Column("id", sa.String(60), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("geometry_geojson", sa.Text, nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="open"),
        sa.Column("conflicting_sources", sa.Text, nullable=True),
        sa.Column("depends_on_bridge_id", sa.String(60), sa.ForeignKey("bridges.id"), nullable=True),
        *_provenance_columns(),
    )

    op.create_table(
        "shelters",
        sa.Column("id", sa.String(60), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("capacity", sa.Integer, nullable=False, server_default="0"),
        sa.Column("occupied", sa.Integer, nullable=False, server_default="0"),
        sa.Column("operational_status", sa.String(20), nullable=False, server_default="operational"),
        sa.Column("accessibility", sa.String(200), nullable=True),
        sa.Column("lat", sa.Float, nullable=False),
        sa.Column("lon", sa.Float, nullable=False),
        *_provenance_columns(),
    )

    op.create_table(
        "hospitals",
        sa.Column("id", sa.String(60), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("emergency_beds", sa.Integer, nullable=False, server_default="0"),
        sa.Column("available_beds", sa.Integer, nullable=False, server_default="0"),
        sa.Column("operational_status", sa.String(20), nullable=False, server_default="operational"),
        sa.Column("lat", sa.Float, nullable=False),
        sa.Column("lon", sa.Float, nullable=False),
        *_provenance_columns(),
    )

    op.create_table(
        "response_resources",
        sa.Column("id", sa.String(60), primary_key=True),
        sa.Column("type", sa.String(80), nullable=False),
        sa.Column("agency", sa.String(120), nullable=False),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="1"),
        sa.Column("availability", sa.String(20), nullable=False, server_default="available"),
        sa.Column("status", sa.String(40), nullable=False, server_default="ready"),
        sa.Column("lat", sa.Float, nullable=False),
        sa.Column("lon", sa.Float, nullable=False),
        *_provenance_columns(),
    )

    op.create_table(
        "verification_records",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("asset_type", sa.String(40), nullable=False),
        sa.Column("asset_id", sa.String(60), nullable=False, index=True),
        sa.Column("status", sa.String(40), nullable=False),
        sa.Column("verified_by", sa.String(200), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(60), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("district", sa.String(120), nullable=False, server_default="Uttarakhand"),
        sa.Column("phase", sa.String(20), nullable=False, server_default="idle"),
        sa.Column("clock_seconds", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_simulated", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "scenario_snapshots",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("scenario_id", sa.String(60), nullable=False, index=True),
        sa.Column("reason", sa.String(40), nullable=False),
        sa.Column("state_json", sa.Text, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("scenario_snapshots")
    op.drop_table("scenarios")
    op.drop_table("verification_records")
    op.drop_table("response_resources")
    op.drop_table("hospitals")
    op.drop_table("shelters")
    op.drop_table("road_segments")
    op.drop_table("bridges")
    op.drop_table("settlements")
    op.drop_table("disaster_events")
    op.drop_table("sources")
